Rails プロジェクトをDocker化
private-ryomann/rails-docker pull request #1
Opened 2023-05-24 14:04 UTC by private-ryomann

## やったこと
RailsプロジェクトをDocker化＋DBをpostgresに変更しました。
- Dockerifleの作成
- docker-compose.ymlの作成
- .envファイルの作成
- database.ymlファイルの編集
- READ.mdに使い方の説明を記載
を行いました。

## 動作確認方法
1. git clone する
2. プロジェクトルートでdocker-compose up -d 
3. ブラウザでlocalhost:3000にアクセス

## その他
確認よろしくお願いします。
* レビュワーへの参考情報（実装上の懸念点や注意点、困りごとなど）

2023-05-24 21:51 UTC, ihatov08 requested changes
CIが落ちているので修正お願いします！

2023-05-25 01:59 UTC, ihatov08 commented
bin以下のファイルパーミッションは変更しないようにお願いします。

2023-05-25 03:46 UTC, private-ryomann commented
dockerのボリュームマウント時のパーミッションについていろいろ調べています。
一番簡単にできそうなのはbin以下のコマンドの部分はchmod +xで実行権限を付けるのかなと考えたのですが、
bin以下のパーミッションを変えてはいけないということなので
方針的には、コンテナ側のuid:gidをホスト側のuid:gidを合わせるという方針で問題ないでしょうか？

2023-05-25 04:56 UTC, ihatov08 commented
bin/railsのような形で実行するのでbin以下は実行権限つける必要ないです。

> 方針的には、コンテナ側のuid:gidをホスト側のuid:gidを合わせるという方針で問題ないでしょうか？

こちらも対応しなくてもrailsは動作するはずです。

2023-05-25 10:51 UTC, private-ryomann commented
ローカルでは特にpermissionエラーが出ずに、
CIで実行されている
docker compose build
docker compose run --rm web bin/setup

などが問題なく実行できているのでよくわかりません。
CIに書かれている
runの部分をいじってみても大丈夫でしょうか？
現在の自分のユーザーやbin/setupなどのパミッションなどを確認したいです。

2023-05-25 11:59 UTC, ihatov08 commented
bin以下のファイルのパーミッションをもとに戻してもらうとciでも動くと思います。
ciのコードは私も他の方もそのままで動いているので、いじらずそのままでお願いします。

2023-05-25 22:11 UTC, ihatov08 commented on .env
> +POSTGRES_PASSWORD=postgres
.envファイルは機密情報を含む場合があるので、コミットに含めないほうがよいでしょう。

.env.exampleで設定する環境変数例を記載するとよいでしょう。

またYARN_VERSIONやPOSTGRES_PASSWORDはcompose.ymlに直接書くで十分だと思います。

https://twitter.com/poly_soft/status/1508709961182101508

2023-05-25 22:49 UTC, private-ryomann commented
修正しました。
.envは使う際は
- .gitignoreに書くようにする
- .env.exampleで設定する環境変数例を記載する

ようにします。
POSTGRES_PASSWORDは秘密情報ではなく実務でも実際にcompose.ymlに直接書かれているものなのでしょうか？
PASSWORDという文字が含まれていたので秘匿情報化と思っていました。

2023-05-26 00:05 UTC, ihatov08 commented
> POSTGRES_PASSWORDは秘密情報ではなく実務でも実際にcompose.ymlに直接書かれているものなのでしょうか？

はい！
PASSWORDですが開発環境では固定値を設定するので開発環境においては秘匿扱いにはならないです！

2023-05-26 00:25 UTC, private-ryomann commented
> PASSWORDですが開発環境では固定値を設定するので開発環境においては秘匿扱いにはならないです！
納得しました！

他に懸念点がなければ、マージしてもよろしいですか？

> > POSTGRES_PASSWORDは秘密情報ではなく実務でも実際にcompose.ymlに直接書かれているものなのでしょうか？
> 
> はい！ PASSWORDですが開発環境では固定値を設定するので開発環境においては秘匿扱いにはならないです！

2023-05-26 00:27 UTC, ihatov08 approved these changes
LGTMです！
マージOKです！

2023-05-26 00:43 UTC, merged